# US - Baby Names



### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset

In [2]:
pd.read_csv("6_US_Baby_Names - 6_US_Baby_Names.csv")

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 3. Assign it to a variable called baby_names.

In [3]:
baby_names = pd.read_csv("6_US_Baby_Names - 6_US_Baby_Names.csv")

### Step 4. See the first 10 entries

In [4]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [5]:
# baby_names.drop(columns=["Unnamed: 0"],inplace=True)
baby_names.drop(columns=["Id"],inplace=True)

### Step 6. Is there more male or female names in the dataset?

In [6]:
baby_names.groupby('Gender')['Count'].sum()

Gender
F    16380293
M    19041199
Name: Count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [7]:
names = baby_names.groupby('Name').agg(Count =('Name','count')).reset_index()
names

          Name  Count
0        Aaban      2
1        Aadan      4
2      Aadarsh      1
3        Aaden    196
4       Aadhav      1
...        ...    ...
17627     Zyra      7
17628    Zyrah      2
17629    Zyren      1
17630    Zyria     10
17631   Zyriah      9

[17632 rows x 2 columns]

### Step 8. How many different names exist in the dataset?

In [9]:
names.Name.nunique()

17632

### Step 9. What is the name with most occurrences?

In [12]:
names.sort_values('Count',ascending=False)[0:1]

        Name  Count
14062  Riley   1112

### Step 10. How many different names have the least occurrences?

In [13]:
names.sort_values('Count',inplace=True)
names[names.Count == 1].size

7364

### Step 11. What is the median name occurrence?

In [15]:
names.Count.median()

np.float64(8.0)

### Step 12. What is the standard deviation of names?

In [16]:
names.Count.std()

np.float64(122.02996350813889)

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [17]:
names.describe()

              Count
count  17632.000000
mean      57.644907
std      122.029964
min        1.000000
25%        2.000000
50%        8.000000
75%       39.000000
max     1112.000000