### Step 1. Import the necessary libraries.

In [1]:
import pandas as pd

### Step 2. Import the dataset.

In [2]:
pd.read_csv("8_music_streaming_habits_2026 - 8_music_streaming_habits_2026.csv")

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

### Step 3. Assign it to a variable called music.

In [3]:
music = pd.read_csv("8_music_streaming_habits_2026 - 8_music_streaming_habits_2026.csv")

### Step 4. Display the first 10 rows of the dataset.

In [4]:
music.head(10)

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
5,6,41,Australia,Tidal,Free,Rock,Olivia Rodrigo,64,19,10,12.0,True,Energetic,False,True
6,7,13,Australia,Spotify,Free,EDM,Burna Boy,193,53,7,20.3,True,Sleep,False,False
7,8,22,India,SoundCloud,Premium,Hip-Hop,Bad Bunny,142,44,7,33.3,False,Workout,False,False
8,9,40,Australia,Spotify,Free,Hip-Hop,Bad Bunny,120,38,7,15.4,True,Happy,False,True
9,10,27,Nigeria,Spotify,Student,Hip-Hop,Burna Boy,127,33,8,48.7,True,Happy,False,True

### Step 6. What is the number of columns in the dataset?

In [5]:
music.shape[1]

15

### Step 7. Print the names of all the columns.

In [6]:
music.columns

Index(['listener_id', 'age', 'country', 'platform', 'subscription',
       'top_genre', 'top_artist', 'daily_listening_minutes', 'songs_per_day',
       'playlists_count', 'skip_rate_pct', 'discover_weekly_user', 'top_mood',
       'uses_offline_mode', 'podcasts_too'],
      dtype='str')

### Step 8. Display the data types of each column.

In [7]:
music.dtypes

listener_id                  int64
age                          int64
country                        str
platform                       str
subscription                   str
top_genre                      str
top_artist                     str
daily_listening_minutes      int64
songs_per_day                int64
playlists_count              int64
skip_rate_pct              float64
discover_weekly_user          bool
top_mood                       str
uses_offline_mode             bool
podcasts_too                  bool
dtype: object

### Step 9. How is the dataset indexed?

In [8]:
music.index

RangeIndex(start=0, stop=4000, step=1)

### Step 10. Display the last 10 rows of the dataset.

In [9]:
music.tail(10)

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
3990,3991,27,Canada,Spotify,Free,R&B,Travis Scott,165,53,9,24.7,True,Happy,False,False
3991,3992,40,Canada,Apple Music,Family,Pop,Olivia Rodrigo,76,18,7,41.6,False,Focus,False,False
3992,3993,35,USA,Spotify,Free,Hip-Hop,The Weeknd,55,19,13,57.3,False,Chill,True,True
3993,3994,37,USA,Spotify,Free,Hip-Hop,Travis Scott,57,20,3,31.9,True,Energetic,True,False
3994,3995,30,Nigeria,Apple Music,Family,Rock,Travis Scott,303,90,10,13.5,True,Sad,True,True
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

### Step 11. Which country has the highest number of listeners?

### Step 12. Which music platform is used by the most listeners?

### Step 13. How many users have Premium and Free subscriptions?

### Step 14. Which is the most popular music genre?

### Step 15. Which artist appears most frequently as the users' top artist?

### Step 16. What is the average daily listening time (in minutes) of all users?

### Step 17. Which listener has the highest daily listening time?

### Step 18. What is the average number of songs listened to per day?

### Step 19. Which country has the highest average daily listening time?

### Step 20. What is the average skip rate percentage across all users?

### Step 21. How many users have enabled offline mode?

### Step 22. How many users listen to podcasts along with music?

### Step 23. What percentage of users use the Discover Weekly feature?

### Step 24. Which mood (top_mood) is the most common among listeners?

### Step 25. What is the average number of playlists created by users?

### Step 29. Which country has the largest number of Premium subscribers?

### Step 30. Create a summary table showing the average listening minutes, songs per day, and skip rate for each platform.