In [1]:
import pandas as pd

In [2]:
data = [['Alice',25,"Delhi"],
        ["Raj",30,"Mumbai"],
        ["Carl",35,"Bhopal"]]

df = pd.DataFrame(data,columns=["Name","Age","City"])

In [3]:
df

    Name  Age    City
0  Alice   25   Delhi
1    Raj   30  Mumbai
2   Carl   35  Bhopal

In [4]:
data = {"Name":["Alice","Raj","Carl"],
        "Age":[30,25,35],
        "Cilt":["Delhi","Mumbai","Bhopal"]}
dr=pd.DataFrame(data)
print(df)

    Name  Age    City
0  Alice   25   Delhi
1    Raj   30  Mumbai
2   Carl   35  Bhopal

In [5]:
df.set_index("Name",inplace=True)

In [6]:
df

       Age    City
Name
Alice   25   Delhi
Raj     30  Mumbai
Carl    35  Bhopal

In [7]:
df.reset_index(inplace=True)

In [8]:
df

    Name  Age    City
0  Alice   25   Delhi
1    Raj   30  Mumbai
2   Carl   35  Bhopal

In [9]:
df = pd.read_csv("data- - data-.csv")
df

    name  age     city category  sales  a   b
0   John   25    Delhi        A    200  5  10
1   Riya   22   Mumbai        B    120  2   3
2   Aman   30     Pune        A    250  7   8
3   Neha   27  Kolkata        C    300  4   6
4  Arjun   35   Jaipur        B    200  1   9

In [10]:
df.shape

(5, 7)

In [11]:
df = pd.read_csv("1_data - 1_data.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: '1_data - 1_data.csv'

In [ ]:
df.shape

(4622, 5)

In [ ]:
df.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [ ]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [ ]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [ ]:
df.values

array([[1, 1, 'Chips and Fresh Tomato Salsa', nan, '$2.39'],
       [1, 1, 'Izze', '[Clementine]', '$3.39'],
       [1, 1, 'Nantucket Nectar', '[Apple]', '$3.39'],
       ...,
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Guacamole, Lettuce]]',
        '$11.25'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Lettuce]]', '$8.75'],
       [1834, 1, 'Chicken Salad Bowl',
        '[Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Lettuce]]',
        '$8.75']], shape=(4622, 5), dtype=object)

In [ ]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [ ]:
df.tail(5)

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df.sample(5)

,order_id,quantity,item_name,choice_description,item_price
3650,1459,1,Chips and Tomatillo-Red Chili Salsa,NaN,$2.39
3499,1405,1,Bottled Water,NaN,$1.09
317,138,1,Canned Soda,[Diet Coke],$1.09
1056,435,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
2705,1074,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$8.75

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [ ]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [ ]:
df.isnull()

      order_id  quantity  item_name  choice_description  item_price
0        False     False      False                True       False
1        False     False      False               False       False
2        False     False      False               False       False
3        False     False      False                True       False
4        False     False      False               False       False
...        ...       ...        ...                 ...         ...
4617     False     False      False               False       False
4618     False     False      False               False       False
4619     False     False      False               False       False
4620     False     False      False               False       False
4621     False     False      False               False       False

[4622 rows x 5 columns]

In [ ]:
df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(1246)

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4617    False
4618    False
4619    False
4620    False
4621    False
Length: 4622, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(59)

In [ ]:
df.set_index("order_id", inplace=True)
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
df['item_name']

order_id
1                Chips and Fresh Tomato Salsa
1                                        Izze
1                            Nantucket Nectar
1       Chips and Tomatillo-Green Chili Salsa
2                                Chicken Bowl
                        ...
1833                            Steak Burrito
1833                            Steak Burrito
1834                       Chicken Salad Bowl
1834                       Chicken Salad Bowl
1834                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: str

In [ ]:
df["quantity"].sum()
df["quantity"].max()

np.int64(15)

In [ ]:
df.sum(numeric_only=True)

quantity    4972
dtype: int64

In [ ]:
df.mode

<bound method DataFrame.mode of           quantity                              item_name  \
order_id
1                1           Chips and Fresh Tomato Salsa
1                1                                   Izze
1                1                       Nantucket Nectar
1                1  Chips and Tomatillo-Green Chili Salsa
2                2                           Chicken Bowl
...            ...                                    ...
1833             1                          Steak Burrito
1833             1                          Steak Burrito
1834             1                     Chicken Salad Bowl
1834             1                     Chicken Salad Bowl
1834             1                     Chicken Salad Bowl

                                         choice_description item_price
order_id
1                                                       NaN      $2.39
1                                              [Clementine]      $3.39
1                                                   [Apple]      $3.39
1                                                       NaN      $2.39
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $16.98
...                                                     ...        ...
1833      [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     $11.75
1833      [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     $11.75
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $11.25
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      $8.75
1834      [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      $8.75

[4622 rows x 4 columns]>

In [ ]:
df.sum().mean

<bound method Series.mean of quantity                                                           4972
item_name             Chips and Fresh Tomato SalsaIzzeNantucket Nect...
choice_description    [Clementine][Apple][Tomatillo-Red Chili Salsa ...
item_price            $2.39$3.39$3.39$2.39$16.98$10.98$1.69$11.75$9....
dtype: object>

In [ ]:
df.rename(columns={'order_id':'id'},inplace=True)

In [ ]:
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
# df['id

In [ ]:
# df[['id','quantity','item_name']]

In [ ]:
df[0:4]
df[0:10]

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
3,1,Side of Chips,NaN,$1.69
4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [ ]:
df.iloc[0:4]

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [ ]:
df['item_price']

order_id
1        $2.39
1        $3.39
1        $3.39
1        $2.39
2       $16.98
         ...
1833    $11.75
1833    $11.75
1834    $11.25
1834     $8.75
1834     $8.75
Name: item_price, Length: 4622, dtype: str

In [ ]:
# df['item_price'].astype(int)

In [ ]:
df['item_price'] = df['item_price'].str.replace('$','',regex=False)

In [ ]:
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,Izze,[Clementine],3.39
1,1,Nantucket Nectar,[Apple],3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df['item_price'] = df['item_price'].str.replace(' ','',regex=False)

In [ ]:
df

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,Izze,[Clementine],3.39
1,1,Nantucket Nectar,[Apple],3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df['item_price'].astype(float)

order_id
1        2.39
1        3.39
1        3.39
1        2.39
2       16.98
        ...
1833    11.75
1833    11.75
1834    11.25
1834     8.75
1834     8.75
Name: item_price, Length: 4622, dtype: float64

In [ ]:
# df['item_price'].between(11,16)

In [ ]:
# df.drop(columns=['id'],inplace=True)

In [ ]:
df = df.drop(columns=['quantity'])

In [ ]:
df

,item_name,choice_description,item_price
order_id,,,
1,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
1,Nantucket Nectar,[Apple],3.39
1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...
1833,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
1833,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1834,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
1834,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1834,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [ ]:
df['item_price'].unique()

<StringArray>
[ '2.39',  '3.39', '16.98', '10.98',  '1.69', '11.75',  '9.25',  '4.45',
  '8.75', '11.25',  '8.49',  '2.18',  '8.99',  '1.09',  '2.95',  '2.15',
  '3.99', '22.50', '11.48', '17.98', '17.50',  '4.30',  '5.90',  '1.25',
 '23.78',  '6.49', '11.08',  '1.50', '22.16', '32.94', '22.20', '10.58',
  '2.50', '23.50',  '7.40', '18.50',  '3.00',  '6.78', '11.89',  '9.39',
  '4.00',  '3.75',  '8.69',  '2.29',  '8.90',  '3.27',  '3.89',  '8.19',
 '35.00', '27.75', '11.80',  '6.00', '26.25', '21.96',  '4.36',  '7.50',
  '4.78', '13.35',  '6.45',  '5.07', '22.96',  '7.17',  '7.98',  '4.50',
 '26.07', '12.98', '35.25', '44.25', '10.50', '33.75', '16.38', '13.52',
  '5.00', '15.00',  '8.50', '17.80',  '1.99', '11.49']
Length: 78, dtype: str

In [ ]:
df['item_price']=pd.to_numeric(df['item_price'])

In [ ]:
df['item_price'].between(11,16)

order_id
1       False
1       False
1       False
1       False
2       False
        ...
1833     True
1833     True
1834     True
1834    False
1834    False
Name: item_price, Length: 4622, dtype: bool

In [ ]:
df[df['item_price'].between(11,16)]

,item_name,choice_description,item_price
order_id,,,
4,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
7,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
19,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
20,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
20,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",11.75
...,...,...,...
1830,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1830,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
1833,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
1833,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1834,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

In [ ]:
df.duplicated().sum()

np.int64(2662)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum().sum()

np.int64(45)

In [ ]:
# df.dropna(inplace=True)

In [ ]:
df

,item_name,choice_description,item_price
order_id,,,
1,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
1,Nantucket Nectar,[Apple],3.39
1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...
1827,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
1829,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
1830,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1830,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
1831,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25

In [ ]:
df.isnull().sum().sum()

np.int64(45)

In [ ]:
df['choice_description'].mode()

0    [Fresh Tomato Salsa, [Rice, Black Beans, Chees...
Name: choice_description, dtype: str

In [ ]:
df.fillna(df['choice_description'].mode(),inplace=True)

,item_name,choice_description,item_price
order_id,,,
1,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
1,Nantucket Nectar,[Apple],3.39
1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...
1827,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
1829,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
1830,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1830,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
1831,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25