In [1]:
import pandas as pd

In [2]:
import numpy as np
arr = np.arange(1,20)
b = pd.Series(arr)
data = pd.DataFrame(arr)
c = pd.DataFrame([arr,arr,arr,arr])
print(arr)
print(b)
print(data)
print(c)
print(np.dtype(b))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64
     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
1   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
2   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
3   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
int64

In [3]:
c = pd.DataFrame({'x':arr,'y':arr,'z':arr})
c

     x   y   z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15
15  16  16  16
16  17  17  17
17  18  18  18
18  19  19  19

In [4]:
df=pd.read_csv('data- - data-.csv')
df
df.head(2)

   name  age    city category  sales  a   b
0  John   25   Delhi        A    200  5  10
1  Riya   22  Mumbai        B    120  2   3

In [5]:
df.tail(1)
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   age       5 non-null      int64
 2   city      5 non-null      str
 3   category  5 non-null      str
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes

             age       sales         a          b
count   5.000000    5.000000  5.000000   5.000000
mean   27.800000  214.000000  3.800000   7.200000
std     4.969909   66.932802  2.387467   2.774887
min    22.000000  120.000000  1.000000   3.000000
25%    25.000000  200.000000  2.000000   6.000000
50%    27.000000  200.000000  4.000000   8.000000
75%    30.000000  250.000000  5.000000   9.000000
max    35.000000  300.000000  7.000000  10.000000

In [6]:
import numpy as np 
import pandas as pd 

a = [10,20,30,40,50]
dic = {"a":10,"b":20,"c":30,"d":40} 
s = pd.Series(dic)
print(s)
print(pd.Series(a))

a    10
b    20
c    30
d    40
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64

## *Series Attribute*

In [7]:
s.size
s.dtype
s.is_unique
s.index
s.head(1)
s.tail(1)

d    40
dtype: int64

In [8]:
arr = np.arange(100,1000)
s = pd.Series(arr)
print(s)

0      100
1      101
2      102
3      103
4      104
      ...
895    995
896    996
897    997
898    998
899    999
Length: 900, dtype: int64

In [9]:
s.head(10)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64

In [10]:
s.tail(10)

890    990
891    991
892    992
893    993
894    994
895    995
896    996
897    997
898    998
899    999
dtype: int64

In [11]:
s.sample(10)

820    920
164    264
700    800
752    852
89     189
205    305
389    489
86     186
516    616
366    466
dtype: int64

In [12]:
s.value_counts()

100    1
101    1
102    1
103    1
104    1
      ..
995    1
996    1
997    1
998    1
999    1
Name: count, Length: 900, dtype: int64

In [13]:
s.sort_values(ascending=False)

899    999
898    998
897    997
896    996
895    995
      ...
4      104
3      103
2      102
1      101
0      100
Length: 900, dtype: int64

In [14]:
s.sort_index()

0      100
1      101
2      102
3      103
4      104
      ...
895    995
896    996
897    997
898    998
899    999
Length: 900, dtype: int64

In [15]:
s.head(100).sample(10).tail(5).sort_index().sort_values(ascending=False)

76    176
75    175
57    157
26    126
1     101
dtype: int64

## *Mataematical Function*

In [16]:
s.count()

np.int64(900)

In [17]:
arr = np.array([1,7,3,2,5,7,8,9,1,3,8,9,np.nan,np.nan,np.nan])
print(arr)
s = pd.Series(arr)
print(s)

[ 1.  7.  3.  2.  5.  7.  8.  9.  1.  3.  8.  9. nan nan nan]
0     1.0
1     7.0
2     3.0
3     2.0
4     5.0
5     7.0
6     8.0
7     9.0
8     1.0
9     3.0
10    8.0
11    9.0
12    NaN
13    NaN
14    NaN
dtype: float64

In [18]:
u = s.size

In [19]:
v=s.count()

In [20]:
a = u - v
print(a)

3

In [21]:
s.sum()

np.float64(63.0)

In [22]:
s.product()

np.float64(22861440.0)

In [23]:
s.mean()

np.float64(5.25)

In [24]:
s.mode()

0    1.0
1    3.0
2    7.0
3    8.0
4    9.0
dtype: float64

In [25]:
s.std()

np.float64(3.1079078025403053)

In [26]:
s.var()

np.float64(9.659090909090908)

In [27]:
s.min()

np.float64(1.0)

In [28]:
s.max()

np.float64(9.0)

In [29]:
s.describe()

count    12.000000
mean      5.250000
std       3.107908
min       1.000000
25%       2.750000
50%       6.000000
75%       8.000000
max       9.000000
dtype: float64

## *Indexing And Slicing*

In [30]:
s.iloc[3]

np.float64(2.0)

In [31]:
s = pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [32]:
s.iloc[1]
s.iloc[[1,3]]
s.iloc[1:3]

b    20
c    30
dtype: int64

In [33]:
s.loc['a']
#s.loc[['a','e']]

np.int64(10)

## *Editing a Series*

In [34]:
s[0]=100
s
s.iloc[5]
s
s[14]=25
s

a      10
b      20
c      30
d      40
e      50
0     100
14     25
dtype: int64

In [35]:
s['a':'c']=[200,300,400]
s

a     200
b     300
c     400
d      40
e      50
0     100
14     25
dtype: int64

In [36]:
s['a':'c']=25
s

a      25
b      25
c      25
d      40
e      50
0     100
14     25
dtype: int64

## *Null Value Handling*

In [37]:
arr = np.array([1,7,3,2,5,7,8,9,1,3,8,9,np.nan,np.nan,np.nan])
print(arr)
s = pd.Series(arr)
s.isnull().sum()

[ 1.  7.  3.  2.  5.  7.  8.  9.  1.  3.  8.  9. nan nan nan]

np.int64(3)

In [38]:
s.notnull().sum()

np.int64(12)

In [39]:
s.hasnans

True

## *Unique Value*

In [40]:
s.unique()

array([ 1.,  7.,  3.,  2.,  5.,  8.,  9., nan])

In [41]:
s.nunique()

7

In [42]:
s.is_unique

False

## *Python Inbuild Function*

In [43]:
s.max()
print(len(s))
print(type(s))
print(dir(s))

print(sorted(s))

15
<class 'pandas.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
[1.0, 1.0, 2.0, 3.0, 3.0, 5.0, 7.0, 7.0, 8.0, 8.0, 9.0, 9.0, nan, nan, nan]

In [44]:
arr = np.array([10,72,35,28,52,73,8,95,18,30,40,9])
print(arr)
s = pd.Series(arr)
#s.isnull().sum()
#print(s.astype(int))
#print(s.astype(float))
# print(s.astype(bool))
# print(s.astype(str))

[10 72 35 28 52 73  8 95 18 30 40  9]

In [45]:
list(s)
tuple(s)
set(s)
dict(s)

{0: np.int64(10),
 1: np.int64(72),
 2: np.int64(35),
 3: np.int64(28),
 4: np.int64(52),
 5: np.int64(73),
 6: np.int64(8),
 7: np.int64(95),
 8: np.int64(18),
 9: np.int64(30),
 10: np.int64(40),
 11: np.int64(9)}

## *Mambership Operator*

In [46]:
print(0 in s)
print(99 in s)
print(s.isin([18]))
print(s.isin([10,30,40]))

True
False
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
dtype: bool
0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
dtype: bool

## *Looping Over a Series*

In [47]:
#for i in s:
 #   print(i)

# for i in s.index:
#     print(i)
    
for i,v in s.items():
    print(i,v)

0 10
1 72
2 35
3 28
4 52
5 73
6 8
7 95
8 18
9 30
10 40
11 9

In [48]:
def double(a):
    return a*a

s.apply(double)

0      100
1     5184
2     1225
3      784
4     2704
5     5329
6       64
7     9025
8      324
9      900
10    1600
11      81
dtype: int64

## *Arthematic Operators*

In [49]:
s+5
s-5
s*5
s/5
s%5
s**4

0        10000
1     26873856
2      1500625
3       614656
4      7311616
5     28398241
6         4096
7     81450625
8       104976
9       810000
10     2560000
11        6561
dtype: int64

In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

s1 = pd.Series(arr1)
s2 = pd.Series(arr2)

s1 + s2
s1 * s2

0     6
1    14
2    24
3    36
4    50
dtype: int64

## *Comparison Operator*

In [51]:
s<5
s>5
s<=5
s>=5
s==5
s==40

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [52]:
s.between(10,40)

0      True
1     False
2      True
3      True
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11    False
dtype: bool

In [53]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

s1 = pd.Series(arr1)
s2 = pd.Series(arr2)

print(s1>s2)
print(s1<s2)
print(s1<=s2)
print(s1>=s2)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool